### ISSUE TITLE
Crashing in my 1.18.2 modpack

### ISSUE THREAD

**Issue by TheButterbrotMan** [FoxShadew/Foxes#4]
https://bytebin.lucko.me/Q80pEcb1M0

**Comment by Sunconure11** [comment]
It's mixin-related, likely related to 1.18.2 itself.

https://pastebin.com/Rq1z6wb1

**Comment by Sunconure11** [comment]
@FoxShadew

**Comment by FoxSamu** [comment]
Ahhh I think it might be an issue with the mixin processor at build time

Might have to build specifically for 1.18.2, at the time of the 1.18 port I had not expected 1.18.2 to be even released, nor to break the mod if it did

Not really able to do much anytime soon due to more important stuff than modding

**Comment by FoxSamu** [comment]
Closing this in favor of #5, same issue but more complete. Will fix it as soon as I get to it, I'm just not coding much lately.
